branchName: '${issue.number}-${issue.title,}'
branches:
  - label: feature
    prefix: feature/
  - label: fix
    prefix: fix/

gitSafeReplacementChar: '-'

defaultBranch: 'main'

autoLinkIssue: true
autoCloseIssue: true

commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'

openDraftPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
prSkipCI: true
conventionalPrTitles: true
conventionalLabels:
  '*':
    '[${branchName}] '
