name: filebeat

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /aicare/b2g/log/*.log
      - /aicare/b2g/log/**/*.log

output.logstash:
  hosts: ["logstash:5044"]

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

## HTTP endpoint for health checking
http:
  enabled: true
  host: 0.0.0.0