name: Manage Issue Branch

on:
  issues:
    types: [ assigned ]
  pull_request:
    types: [ closed ]

jobs:
  manage_issue_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Manage issue branch
        id: manage_issue_branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Echo branch name
        run: echo ${{ steps.manage_issue_branch.outputs.branchName }}