name: Java build test with gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    outputs:
      build-output: ${{ steps.artifact-upload-step.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: '8.5'
          cache-read-only: false

      - name: Build with Gradle Wrapper
        run: |
          gradle wrapper
          ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: monitoring-build-result
          #          path: ~/build-result/
          path: ./build/
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true

  execution:
    name: Execute project

    needs: build
    runs-on: ubuntu-latest

    steps:
      - env:
          BUILD-OUTPUT: ${{ needs.build.outputs.build-output }}
        run: echo "artifact id from previous job is $BUILD-OUTPUT"

      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: monitoring-build-result
          path: ./build/

      - name: Execute server application
        run: java -jar build/libs/aicare-monitoring-0.0.1-SNAPSHOT.jar

  dependency-submission:
    name: Dependency submission

    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: 8.5