name: Java build test with gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    outputs:
      project-name: ${{ steps.build-info.outputs.project-name }}
      build-version: ${{ steps.build-info.outputs.build-version }}
      filename: ${{ steps.build-info.outputs.filename }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: '8.5'
          cache-read-only: false

      - name: Build with Gradle Wrapper
        run: |
          gradle wrapper
          ./gradlew build -x test

      - name: Extract version and root project name
        id: build-info
        run: |
          VERSION=$(grep "^version" build.gradle | awk -F"'" '{print $2}')
          ROOT_PROJECT=$(grep "^rootProject.name" settings.gradle | awk -F"'" '{print $2}')
          echo "project-name=$ROOT_PROJECT" >> $GITHUB_OUTPUT
          echo "build-version=$VERSION" >> $GITHUB_OUTPUT
          echo "filename=$ROOT_PROJECT-$VERSION" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: monitoring-build-result
          path: ./build/
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true

  execution:
    name: Execute project

    needs: build-project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: monitoring-build-result
          path: ./build/

      - name: Execute server application
        env:
          FILENAME: ${{ needs.build-project.outputs.filename }}
        run: java -jar build/libs/${{ env.FILENAME }}.jar
        background: true

  dependency-submission:
    name: Submit dependency graph to github

    needs: build-project
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: 8.5

  docker-image:
    name: Upload docker image to docker hub

    needs: build-project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: monitoring-build-result
          path: ./build/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          PROJECT_NAME: ${{ needs.build-project.outputs.project-name }}
          BUILD_VERSION: ${{ needs.build-project.outputs.build-version }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ PROJECT_NAME }}:${{ BUILD_VERSION }}